#!/bin/sh

# Get the current branch name
branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

# Block commits to the main branch
if [ "$branch" = "main" ]; then
    echo "You are on the main branch. Commit blocked."
    exit 1
fi

# Run Prettier and add all changed files to the commit
npm run prettier:check
if [ $? -ne 0 ]; then
    echo "Prettier found issues that need to be resolved."
    exit 1
fi

git add -A
